FROM composer


ENV GID 1000
ENV UID 1000
ENV USERNAME mnr

RUN echo "#!/usr/bin/env bash" > /usr/local/bin/start-container
RUN echo "composer install" >> /usr/local/bin/start-container
RUN echo "tail -f /dev/null" >> /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

RUN addgroup -S $USERNAME -g $GID
RUN adduser -S $USERNAME -G $USERNAME -u $UID

USER $USERNAME

ENTRYPOINT ["start-container"]